package aiimin.core.data.notify

import aiimin.core.data.core.DayClock
import aiimin.core.data.life.LifeRepository
import aiimin.core.data.settings.SettingsStore
import aiimin.core.data.util.Money
import aiimin.core.data.util.newId
import aiimin.core.database.CalendarDao
import aiimin.core.database.MoneyDao
import aiimin.core.database.NotificationDao
import aiimin.core.database.NotificationEntity
import aiimin.core.database.TaskDao
import aiimin.core.database.VaultDao
import aiimin.core.engine.BatteryState
import android.Manifest
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import dagger.hilt.android.qualifiers.ApplicationContext
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.LocalTime
import java.time.YearMonth
import java.time.temporal.ChronoUnit
import java.time.temporal.IsoFields
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Notifications are generated by rules from real state (plan Part 2 §8), never
 * seeded. Each rule has a dedupe key so it fires once. Copy leads with what you
 * can gain, never with damage.
 */
@Singleton
class NotificationRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val dao: NotificationDao,
    private val vault: VaultDao,
    private val tasks: TaskDao,
    private val calendar: CalendarDao,
    private val money: MoneyDao,
    private val life: LifeRepository,
    private val settings: SettingsStore,
    private val clock: DayClock,
) {
    val all = dao.all()
    val unread = dao.unread()
    suspend fun markAllRead() = dao.markAllRead()
    suspend fun dismiss(id: String) = dao.dismiss(id)

    suspend fun run() {
        val today = clock.today()
        val now = LocalTime.now(clock.zone)

        // Documents expiring: 90 / 60 / 30 / 7 / 0 days, most urgent only.
        for (d in vault.withExpiry()) {
            val left = ChronoUnit.DAYS.between(today, LocalDate.parse(d.expires!!))
            val t = listOf(0L, 7L, 30L, 60L, 90L).firstOrNull { left <= it } ?: continue
            if (left < -7) continue
            val body = when {
                left < 0 -> "Expired ${-left} day${if (left == -1L) "" else "s"} ago. Renew and add the new copy."
                left == 0L -> "Expires today."
                else -> "Expires in $left days, on ${LocalDate.parse(d.expires).let { "${it.dayOfMonth} ${it.month.name.lowercase().replaceFirstChar(Char::uppercase).take(3)}" }}."
            }
            emit("doc:${d.id}:$t", d.title, body, "doc", d.id, if (t <= 30) 2 else 1)
        }

        // Events starting within 15 minutes.
        val nowMs = System.currentTimeMillis()
        calendar.betweenNow(nowMs, nowMs + 15 * 60_000L).filter { !it.allDay && it.startAt >= nowMs }.forEach {
            emit("event:${it.id}", it.title, "Starts at ${aiimin.core.data.util.Dates.clock(java.time.Instant.ofEpochMilli(it.startAt).atZone(clock.zone).toLocalTime())}.", "today", it.id, 2)
        }

        // A timed task that passed half an hour ago — gentle, once.
        tasks.forDayNow(today.toString()).filter { !it.done && it.time != null && it.assignee == null }.forEach { t ->
            val at = runCatching { LocalTime.parse(t.time) }.getOrNull() ?: return@forEach
            if (now.isAfter(at.plusMinutes(30))) emit("task:${t.id}:$today", "Still on for today", t.title, "today", t.id, 1)
        }

        // Evening: minimums at risk. Lead with the gain.
        val view = runCatching { life.compute() }.getOrNull()
        if (view != null && now.hour >= 20) {
            val m = view.today.minimums
            val left = m.planned - m.kept
            if (left > 0 && !view.today.paused) {
                emit("streak:$today", "$left minimum${if (left == 1) "" else "s"} left today", "Keep ${if (left == 1) "it" else "them"} and your ${view.readout.streak.current}-day streak carries on.", "today", null, 2)
            }
        }
        if (view?.battery?.state == BatteryState.LOW) {
            emit("battery:$today", "Rough patch — let's restart small", "Today your minimums are the tiny versions, and each counts double.", "today", null, 1)
        }

        // Budget pace on the personal ledger.
        val ym = YearMonth.from(today)
        money.budgetNow(ym.toString())?.let { b ->
            val spent = money.betweenNow(ym.atDay(1).toString(), today.toString()).filter { it.ledger == "PERSONAL" && it.direction == "out" }.sumOf { it.amountPaise }
            if (b.totalPaise > 0) {
                val share = spent * 100 / b.totalPaise
                when {
                    share >= 100 -> emit("budget:$ym:100", "Month plan reached", "${Money.format(spent)} of ${Money.format(b.totalPaise)} spent.", "money", null, 1)
                    share >= 80 -> emit("budget:$ym:80", "80% of the month plan used", "${Money.format(b.totalPaise - spent)} left for ${ym.lengthOfMonth() - today.dayOfMonth + 1} days.", "money", null, 1)
                }
            }
        }

        // Review inbox.
        val pending = money.pendingDraftsNow().size
        if (pending > 0) emit("inbox:$today", "$pending payment${if (pending == 1) "" else "s"} to review", "Detected from your bank alerts. Nothing is booked until you settle it.", "money", null, 0)

        // Weekly review, Sunday evening.
        if (today.dayOfWeek == DayOfWeek.SUNDAY && now.hour >= 18) {
            emit("review:${today.get(IsoFields.WEEK_OF_WEEK_BASED_YEAR)}", "Your week, in one screen", "Five minutes to close the week and set up the next.", "score", null, 0)
        }
    }

    private suspend fun emit(key: String, title: String, body: String, route: String, arg: String?, priority: Int) {
        val n = NotificationEntity(newId(), key, title, body, System.currentTimeMillis(), route, arg, priority)
        if (dao.insertIfNew(n) == -1L) return
        val s = settings.current()
        val mins = LocalTime.now(clock.zone).let { it.hour * 60 + it.minute }
        val quiet = s.quiet.enabled && if (s.quiet.fromMin <= s.quiet.toMin) mins in s.quiet.fromMin until s.quiet.toMin else mins >= s.quiet.fromMin || mins < s.quiet.toMin
        // Quiet hours hold back low and medium; high still comes through.
        if (priority == 0 || (quiet && priority < 2)) return
        post(n)
    }

    private fun post(n: NotificationEntity) {
        if (Build.VERSION.SDK_INT >= 33 && ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) return
        ensureChannels(context)
        val launch = context.packageManager.getLaunchIntentForPackage(context.packageName)?.apply {
            putExtra(EXTRA_ROUTE, n.route)
            putExtra(EXTRA_ARG, n.routeArg)
            addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP)
        }
        val pi = launch?.let { PendingIntent.getActivity(context, n.ruleKey.hashCode(), it, PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT) }
        val notif = NotificationCompat.Builder(context, if (n.priority >= 2) CH_HIGH else CH_DEFAULT)
            .setSmallIcon(android.R.drawable.stat_notify_more)
            .setContentTitle(n.title)
            .setContentText(n.body)
            .setStyle(NotificationCompat.BigTextStyle().bigText(n.body))
            .setContentIntent(pi)
            .setAutoCancel(true)
            .setPriority(if (n.priority >= 2) NotificationCompat.PRIORITY_HIGH else NotificationCompat.PRIORITY_DEFAULT)
            .build()
        runCatching { NotificationManagerCompat.from(context).notify(n.ruleKey.hashCode(), notif) }
    }

    companion object {
        const val CH_HIGH = "aiimin_important"
        const val CH_DEFAULT = "aiimin_general"
        const val CH_FOCUS = "aiimin_focus"
        const val EXTRA_ROUTE = "aiimin.route"
        const val EXTRA_ARG = "aiimin.arg"

        fun ensureChannels(context: Context) {
            val nm = context.getSystemService(NotificationManager::class.java)
            nm.createNotificationChannel(NotificationChannel(CH_HIGH, "Important", NotificationManager.IMPORTANCE_HIGH).apply { description = "Expiring documents, events starting, minimums left today" })
            nm.createNotificationChannel(NotificationChannel(CH_DEFAULT, "General", NotificationManager.IMPORTANCE_DEFAULT).apply { description = "Budget pace, reminders, review" })
            nm.createNotificationChannel(NotificationChannel(CH_FOCUS, "Focus timer", NotificationManager.IMPORTANCE_LOW).apply { description = "The running focus session" })
        }
    }
}
