import React, { useState, useEffect } from 'react';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font, Image } from '@react-pdf/renderer';
import { Download, AlertCircle, Calendar, FileText, CheckCircle } from 'lucide-react';

// Create styles for PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2px solid #3B82F6',
    paddingBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3B82F6',
    marginTop: 20,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    borderBottom: '1px solid #E5E7EB',
    paddingVertical: 8,
  },
  label: {
    width: '40%',
    fontSize: 12,
    color: '#4B5563',
    fontWeight: 'bold',
  },
  value: {
    width: '60%',
    fontSize: 12,
    color: '#111827',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 10,
    borderTop: '1px solid #E5E7EB',
    paddingTop: 10,
  }
});

// The PDF Document Component
const ReportDocument = ({ data, timeline }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>AIIMIN System Report</Text>
        <Text style={styles.subtitle}>Confidential & Personal · {timeline}</Text>
      </View>
      
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={{ fontSize: 12, color: '#4B5563', lineHeight: 1.5, marginBottom: 15 }}>
          This report aggregates your physical, cognitive, and behavioral metrics over the selected timeline. It is designed to provide actionable insights into your system stability, mastery quotient, and physiological baseline.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Key Performance Indicators</Text>
        
        <View style={styles.row}>
          <Text style={styles.label}>Average Sleep Duration</Text>
          <Text style={styles.value}>{data.avgSleep} hrs</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Focus Cycles Completed</Text>
          <Text style={styles.value}>{data.totalFocusCycles}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>DSA Problems Solved</Text>
          <Text style={styles.value}>{data.totalDSA}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Average Mood Score</Text>
          <Text style={styles.value}>{data.avgMood} / 10</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Discipline Integrity</Text>
          <Text style={styles.value}>{data.disciplineScore}%</Text>
        </View>
      </View>
      
      <Text style={styles.footer}>
        Generated by AIIMIN V2 · The Honest Record
      </Text>
    </Page>
  </Document>
);

const PDFReportGenerator = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [eligible, setEligible] = useState(false);
  const [timeline, setTimeline] = useState('Last 15 Days');
  
  useEffect(() => {
    // Mock fetching data and determining eligibility based on > 15 days usage
    const checkEligibility = async () => {
      setLoading(true);
      try {
        // In a real scenario, this would fetch from an API:
        // const res = await api.get('/user/logs?days=15');
        // Let's simulate a network request
        await new Promise(r => setTimeout(r, 1000));
        
        // Mock data
        const mockData = {
          daysLogged: 16, // User must have > 15 to be eligible
          avgSleep: 7.2,
          totalFocusCycles: 45,
          totalDSA: 32,
          avgMood: 7.8,
          disciplineScore: 84
        };
        
        if (mockData.daysLogged >= 15) {
          setEligible(true);
          setData(mockData);
        } else {
          setEligible(false);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    
    checkEligibility();
  }, []);

  if (loading) {
    return (
      <div style={{ padding: '24px', background: 'var(--bg-elevated)', borderRadius: '16px', border: '1px solid var(--color-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', height: '200px' }}>
        <div style={{ color: 'var(--color-text-3)', fontSize: '14px' }}>Analyzing usage data...</div>
      </div>
    );
  }

  if (!eligible) {
    return (
      <div style={{ padding: '32px', background: 'var(--bg-elevated)', borderRadius: '16px', border: '1px dashed var(--color-border)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
          <div style={{ width: '40px', height: '40px', borderRadius: '50%', background: 'rgba(239, 68, 68, 0.1)', color: '#EF4444', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <AlertCircle size={20} />
          </div>
          <div>
            <h3 style={{ margin: 0, fontSize: '16px', color: 'var(--color-text-1)' }}>Insufficient Data for PDF Report</h3>
            <p style={{ margin: '4px 0 0 0', fontSize: '13px', color: 'var(--color-text-3)' }}>We need at least 15 days of usage data to generate a meaningful analysis.</p>
          </div>
        </div>
        <div style={{ background: 'var(--bg-card)', padding: '16px', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '13px', color: 'var(--color-text-2)', fontWeight: 600 }}>Current Usage</span>
            <span style={{ fontSize: '14px', color: 'var(--color-text-1)', fontWeight: 800 }}>In Progress...</span>
        </div>
      </div>
    );
  }

  return (
    <div style={{ padding: '32px', background: 'var(--bg-elevated)', borderRadius: '16px', border: '1px solid var(--color-border)' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '48px', height: '48px', borderRadius: '12px', background: 'var(--accent-alpha)', color: 'var(--color-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <FileText size={24} />
            </div>
            <div>
              <h3 style={{ margin: 0, fontSize: '18px', color: 'var(--color-text-1)', letterSpacing: '-0.02em' }}>In-Depth System Report</h3>
              <p style={{ margin: '4px 0 0 0', fontSize: '13px', color: 'var(--color-text-3)' }}>A comprehensive PDF analysis of your physiological and cognitive metrics.</p>
            </div>
        </div>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 12px', background: 'rgba(16, 185, 129, 0.1)', color: '#10B981', borderRadius: '20px', fontSize: '12px', fontWeight: 700 }}>
            <CheckCircle size={14} /> Data Sufficient
        </div>
      </div>
      
      <div style={{ display: 'flex', gap: '16px', marginBottom: '24px' }}>
        <div style={{ flex: 1 }}>
            <label style={{ display: 'block', fontSize: '11px', fontWeight: 700, color: 'var(--color-text-3)', textTransform: 'uppercase', marginBottom: '8px' }}>Select Timeline</label>
            <div style={{ position: 'relative' }}>
                <Calendar size={16} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--color-text-3)' }} />
                <select 
                    value={timeline} 
                    onChange={(e) => setTimeline(e.target.value)}
                    style={{ 
                        width: '100%', 
                        padding: '12px 12px 12px 40px', 
                        background: 'var(--bg-card)', 
                        border: '1px solid var(--color-border)', 
                        borderRadius: '12px',
                        color: 'var(--color-text-1)',
                        fontSize: '14px',
                        fontWeight: 600,
                        appearance: 'none',
                        outline: 'none',
                        cursor: 'pointer'
                    }}
                >
                    <option value="Last 15 Days">Last 15 Days</option>
                    <option value="Last 30 Days">Last 30 Days</option>
                    <option value="Quarterly">Quarterly Report</option>
                    <option value="All Time">All Time</option>
                </select>
            </div>
        </div>
      </div>
      
      <PDFDownloadLink 
        document={<ReportDocument data={data} timeline={timeline} />} 
        fileName={`AIIMIN_Report_${timeline.replace(/\s+/g, '_')}.pdf`}
        style={{ textDecoration: 'none' }}
      >
        {({ blob, url, loading, error }) => (
          <button 
            disabled={loading}
            style={{ 
                width: '100%', 
                padding: '14px', 
                background: loading ? 'var(--color-border)' : 'var(--color-accent)', 
                color: loading ? 'var(--color-text-3)' : '#fff', 
                border: 'none', 
                borderRadius: '12px', 
                fontSize: '14px', 
                fontWeight: 700, 
                cursor: loading ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                transition: 'all 0.2s ease'
            }}
          >
            <Download size={18} />
            {loading ? 'Generating PDF...' : 'Download PDF Report'}
          </button>
        )}
      </PDFDownloadLink>
    </div>
  );
};

export default PDFReportGenerator;
