-- ============================================================
-- Migration v4b: Money System Overhaul
-- Preserves ALL existing money_transactions data.
-- Run in Supabase SQL editor AFTER v4_habits_routines.sql
-- ============================================================

-- 1. money_categories
--    user_id = NULL → system/shared categories visible to all authenticated users
CREATE TABLE IF NOT EXISTS money_categories (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id    UUID REFERENCES users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    color      TEXT,
    icon       TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default shared categories (idempotent via name uniqueness)
INSERT INTO money_categories (user_id, name, color, icon)
SELECT NULL, v.name, v.color, v.icon
FROM (VALUES
    ('Food',          '#10b981', '🍽️'),
    ('Transport',     '#3b82f6', '🚌'),
    ('Shopping',      '#f59e0b', '🛍️'),
    ('Utilities',     '#6b7280', '⚡'),
    ('Health',        '#ef4444', '💊'),
    ('Entertainment', '#8b5cf6', '🎮'),
    ('Other',         '#6b7280', '📌')
) AS v(name, color, icon)
WHERE NOT EXISTS (
    SELECT 1 FROM money_categories mc
    WHERE mc.user_id IS NULL AND mc.name = v.name
);

-- 2. Extend existing money_transactions (non-breaking, nullable columns)
ALTER TABLE money_transactions
    ADD COLUMN IF NOT EXISTS category_id  UUID REFERENCES money_categories(id),
    ADD COLUMN IF NOT EXISTS description  TEXT,
    ADD COLUMN IF NOT EXISTS currency     TEXT DEFAULT 'INR';

-- 3. recurring — scheduled entries generated by cron only (never on page load)
CREATE TABLE IF NOT EXISTS recurring (
    id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id       UUID REFERENCES users(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    amount        NUMERIC(10,2) NOT NULL,
    category_id   UUID REFERENCES money_categories(id),
    frequency     TEXT NOT NULL CHECK (frequency IN ('daily', 'weekly', 'monthly', 'yearly')),
    next_due_date DATE NOT NULL,
    active        BOOLEAN DEFAULT true,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- 4. budgets — per-category spend limits
CREATE TABLE IF NOT EXISTS budgets (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
    category_id UUID REFERENCES money_categories(id),
    amount      NUMERIC(10,2) NOT NULL,
    period      TEXT NOT NULL DEFAULT 'monthly' CHECK (period IN ('weekly', 'monthly')),
    start_date  DATE NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 5. savings_goals
CREATE TABLE IF NOT EXISTS savings_goals (
    id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id        UUID REFERENCES users(id) ON DELETE CASCADE,
    name           TEXT NOT NULL,
    target_amount  NUMERIC(10,2) NOT NULL,
    current_amount NUMERIC(10,2) DEFAULT 0,
    deadline       DATE,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Row Level Security
-- ============================================================

ALTER TABLE money_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring        ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets          ENABLE ROW LEVEL SECURITY;
ALTER TABLE savings_goals    ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_can_access_money_categories"    ON money_categories;
DROP POLICY IF EXISTS "users_can_access_own_recurring"       ON recurring;
DROP POLICY IF EXISTS "users_can_access_own_budgets"         ON budgets;
DROP POLICY IF EXISTS "users_can_access_own_savings_goals"   ON savings_goals;

-- Categories: system rows (user_id IS NULL) are readable by all authenticated users
CREATE POLICY "users_can_access_money_categories"
    ON money_categories FOR ALL
    USING (user_id IS NULL OR auth.uid() = user_id);

CREATE POLICY "users_can_access_own_recurring"
    ON recurring FOR ALL
    USING (auth.uid() = user_id);

CREATE POLICY "users_can_access_own_budgets"
    ON budgets FOR ALL
    USING (auth.uid() = user_id);

CREATE POLICY "users_can_access_own_savings_goals"
    ON savings_goals FOR ALL
    USING (auth.uid() = user_id);

-- Ensure money_transactions also has RLS (may already have it, guarded by DO block)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename  = 'money_transactions'
          AND policyname = 'users_can_access_own_transactions'
    ) THEN
        ALTER TABLE money_transactions ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "users_can_access_own_transactions"
            ON money_transactions FOR ALL
            USING (auth.uid() = user_id);
    END IF;
END $$;

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_money_transactions_user_date
    ON money_transactions (user_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_recurring_user_due
    ON recurring (user_id, next_due_date) WHERE active = true;

CREATE INDEX IF NOT EXISTS idx_budgets_user_period
    ON budgets (user_id, period, start_date);
