/**
 * ReportPdfUtils.js — Premium PDF design utilities for AIIMIN Life-System Reports
 * Professional-grade report generation with rich data visualization.
 */

// ─── Report Mode Definitions ────────────────────────────────────────────────
export const REPORT_MODES = {
    quick: {
        label: 'Quick Snapshot',
        subtitle: '3 pages · 2 min',
        emoji: '⚡',
        sections: ['coverPage', 'executiveSummary', 'actionPlan'],
    },
    standard: {
        label: 'Weekly Report',
        subtitle: '8 pages · 5 min',
        emoji: '📊',
        sections: ['coverPage', 'executiveSummary', 'lifeHealthRadar', 'habitsAnalysis', 'goalsProgress', 'bestVsWorstDay', 'financialPosture', 'actionPlan'],
    },
    deep: {
        label: 'Deep Analysis',
        subtitle: '14+ pages · 10 min',
        emoji: '🔬',
        sections: ['coverPage', 'executiveSummary', 'lifeHealthRadar', 'systemDiagnostics', 'habitsAnalysis', 'goalsProgress', 'trendAnalysis', 'behaviorDrivers', 'bestVsWorstDay', 'behaviorClusters', 'financialPosture', 'stabilityAndDrift', 'predictions', 'momentumMultiplier', 'actionPlan'],
    },
};

export const PAGE_TITLES = {
    coverPage: 'AIIMIN Life-System Report',
    executiveSummary: 'Executive Summary',
    lifeHealthRadar: 'Life Health Radar',
    systemDiagnostics: 'System Diagnostics',
    habitsAnalysis: 'Habits Analysis',
    goalsProgress: 'Goals Progress',
    trendAnalysis: 'Trend Analysis',
    behaviorDrivers: 'Behavior Drivers',
    bestVsWorstDay: 'Peak vs Trough Days',
    behaviorClusters: 'Behavior Patterns',
    financialPosture: 'Financial Posture',
    stabilityAndDrift: 'Stability & Drift',
    predictions: 'Predictive Trajectory',
    momentumMultiplier: 'Momentum Multiplier',
    actionPlan: 'Action Plan',
};

// ─── Color Palette ───────────────────────────────────────────────────────────
const GOLD = [212, 175, 55];
const GOLD_LIGHT = [245, 221, 137];
const DARK = [20, 20, 30];
const GRAY = [100, 100, 110];
const LIGHT_GRAY = [240, 240, 245];
const GREEN = [34, 197, 94];
const RED = [239, 68, 68];
const BLUE = [59, 130, 246];
const PURPLE = [139, 92, 246];
const ORANGE = [249, 115, 22];
const TEAL = [6, 182, 212];

// ─── Helper: Set font style ──────────────────────────────────────────────────
const setFont = (doc, size, weight = 'normal', color = DARK) => {
    doc.setFont('helvetica', weight);
    doc.setFontSize(size);
    doc.setTextColor(...color);
};

const setFill = (doc, color) => doc.setFillColor(...color);
const setDraw = (doc, color) => doc.setDrawColor(...color);

// ─── Cover Page ──────────────────────────────────────────────────────────────
export function drawCoverPage(doc, { user, startDate, endDate, reportMode }) {
    const W = 210, H = 297;
    
    // Background gradient effect (top bar)
    setFill(doc, DARK);
    doc.rect(0, 0, W, 80, 'F');
    
    // Gold accent stripe
    setFill(doc, GOLD);
    doc.rect(0, 78, W, 2, 'F');
    
    // AIIMIN logo area
    setFont(doc, 11, 'normal', [180, 160, 80]);
    doc.text('AIIMIN LIFE-SYSTEM', 105, 28, { align: 'center' });
    
    setFont(doc, 32, 'bold', [255, 255, 255]);
    doc.text('Personal OS Report', 105, 50, { align: 'center' });
    
    setFont(doc, 12, 'normal', [180, 180, 190]);
    doc.text(`${REPORT_MODES[reportMode]?.label || 'Report'} · ${startDate} – ${endDate}`, 105, 64, { align: 'center' });
    
    // Central decorative element
    setDraw(doc, GOLD);
    doc.setLineWidth(0.3);
    doc.circle(105, 160, 50);
    doc.circle(105, 160, 35);
    
    setFont(doc, 28, 'bold', GOLD);
    doc.text('AI', 105, 164, { align: 'center' });
    
    setFont(doc, 9, 'normal', GOLD);
    doc.text('AIIMIN', 105, 174, { align: 'center' });
    
    // Report info box
    setFill(doc, LIGHT_GRAY);
    doc.roundedRect(30, 230, 150, 40, 3, 3, 'F');
    
    setFont(doc, 9, 'bold', GRAY);
    doc.text('GENERATED BY', 105, 242, { align: 'center' });
    setFont(doc, 12, 'bold', DARK);
    doc.text(user?.name || user?.email || 'AIIMIN User', 105, 253, { align: 'center' });
    setFont(doc, 9, 'normal', GRAY);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`, 105, 263, { align: 'center' });
    
    // Footer
    setFont(doc, 8, 'normal', [150, 150, 160]);
    doc.text('Confidential · AIIMIN Life-System · Personal Operating System', 105, 285, { align: 'center' });
}

// ─── Page Header ─────────────────────────────────────────────────────────────
export function drawHeader(doc, title, subtitle = '') {
    const W = 210;
    
    // Top bar
    setFill(doc, DARK);
    doc.rect(0, 0, W, 22, 'F');
    
    setFont(doc, 8, 'bold', [180, 160, 80]);
    doc.text('AIIMIN', 14, 9);
    setFont(doc, 8, 'normal', [150, 150, 160]);
    doc.text('Life-System Report', 30, 9);
    
    if (subtitle) {
        setFont(doc, 7, 'normal', [120, 120, 130]);
        doc.text(subtitle, W - 14, 9, { align: 'right' });
    }
    
    // Gold underline
    setFill(doc, GOLD);
    doc.rect(0, 21, W, 1, 'F');
    
    // Section title
    setFont(doc, 20, 'bold', DARK);
    doc.text(title, 14, 36);
    
    // Decorative dot
    setFill(doc, GOLD);
    doc.circle(doc.getTextWidth(title) + 17, 33, 1.5, 'F');
}

// ─── Section Sub-Header ──────────────────────────────────────────────────────
export function drawSectionHeader(doc, title, y) {
    setFont(doc, 12, 'bold', DARK);
    doc.text(title, 14, y);
    
    setFill(doc, GOLD);
    doc.rect(14, y + 2, doc.getTextWidth(title), 0.5, 'F');
}

// ─── Separator ───────────────────────────────────────────────────────────────
export function drawSeparator(doc, y) {
    setFill(doc, LIGHT_GRAY);
    doc.rect(14, y, 182, 0.5, 'F');
}

// ─── Metric Card ─────────────────────────────────────────────────────────────
export function drawMetricCard(doc, label, value, x, y, width, options = {}) {
    const { trend = null, color = GOLD, bg = [252, 250, 240], height = 28 } = options;
    
    // Background
    setFill(doc, bg);
    setDraw(doc, [220, 215, 200]);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, width, height, 3, 3, 'FD');
    
    // Left accent bar
    setFill(doc, color);
    doc.roundedRect(x, y, 2, height, 1, 1, 'F');
    
    // Label
    setFont(doc, 7.5, 'normal', GRAY);
    doc.text(label.toUpperCase(), x + 6, y + 8);
    
    // Value
    setFont(doc, 16, 'bold', DARK);
    doc.text(String(value), x + 6, y + 21);
    
    // Trend arrow
    if (trend !== null && !isNaN(trend)) {
        const up = trend > 0;
        const neutral = trend === 0;
        setFont(doc, 9, 'bold', neutral ? GRAY : (up ? GREEN : RED));
        const arrow = neutral ? '→' : (up ? '↑' : '↓');
        doc.text(`${arrow} ${Math.abs(trend)}`, x + width - 16, y + 21);
    }
}

// ─── Score Badge ─────────────────────────────────────────────────────────────
export function drawScoreBadge(doc, score, x, y, radius = 20, label = '') {
    const pct = Math.max(0, Math.min(100, Number(score) || 0));
    const color = pct >= 75 ? GREEN : pct >= 50 ? GOLD : pct >= 30 ? ORANGE : RED;
    
    // Outer circle
    setDraw(doc, LIGHT_GRAY);
    doc.setLineWidth(0.5);
    doc.circle(x, y, radius);
    
    // Score arc (simulate filled)
    setDraw(doc, color);
    doc.setLineWidth(3);
    // Draw a partial circle to represent score (simplified as filled circle)
    setFill(doc, [...color, 20]);
    doc.circle(x, y, radius - 1);
    
    // Score text
    setFont(doc, 16, 'bold', color);
    doc.text(String(pct), x, y + 2, { align: 'center' });
    setFont(doc, 7, 'normal', GRAY);
    if (label) doc.text(label, x, y + radius + 6, { align: 'center' });
}

// ─── Footer ──────────────────────────────────────────────────────────────────
export function addFooter(doc, page, totalPages) {
    doc.setPage(page);
    const W = 210;
    
    setFill(doc, LIGHT_GRAY);
    doc.rect(0, 282, W, 15, 'F');
    
    setFont(doc, 7, 'normal', GRAY);
    doc.text(`AIIMIN Life-System Report`, 14, 290);
    doc.text(`Page ${page} of ${totalPages}`, W - 14, 290, { align: 'right' });
    doc.text(`Confidential · ${new Date().toLocaleDateString()}`, W / 2, 290, { align: 'center' });
}

// ─── Radar Chart ─────────────────────────────────────────────────────────────
export function drawRadarChart(doc, scores = {}, cx = 105, cy = 90) {
    const radius = 40;
    const axes = [
        { key: 'physical', label: 'Physical', angle: -90 },
        { key: 'cognitive', label: 'Cognitive', angle: -18 },
        { key: 'discipline', label: 'Discipline', angle: 54 },
        { key: 'financial', label: 'Financial', angle: 126 },
        { key: 'emotional', label: 'Emotional', angle: 198 },
    ];
    
    // Grid rings
    [0.25, 0.5, 0.75, 1.0].forEach((level, i) => {
        const r = radius * level;
        const points = axes.map(axis => {
            const rad = (axis.angle * Math.PI) / 180;
            return [cx + Math.cos(rad) * r, cy + Math.sin(rad) * r];
        });
        
        setDraw(doc, i === 3 ? [200, 200, 210] : [225, 225, 235]);
        doc.setLineWidth(0.2);
        const path = points.map((pt, idx) => {
            const prev = points[idx === 0 ? points.length - 1 : idx - 1];
            return [pt[0] - prev[0], pt[1] - prev[1]];
        });
        doc.lines(path, points[points.length - 1][0], points[points.length - 1][1]);
    });
    
    // Score labels on rings
    setFont(doc, 6, 'normal', [180, 180, 190]);
    ['25', '50', '75', '100'].forEach((lbl, i) => {
        const r = radius * (i + 1) / 4;
        const rad = (-90 * Math.PI) / 180;
        doc.text(lbl, cx + Math.cos(rad) * r - 2, cy + Math.sin(rad) * r);
    });
    
    // Axis lines + labels
    axes.forEach(axis => {
        const rad = (axis.angle * Math.PI) / 180;
        const x = cx + Math.cos(rad) * radius;
        const y = cy + Math.sin(rad) * radius;
        
        setDraw(doc, [200, 200, 210]);
        doc.setLineWidth(0.2);
        doc.line(cx, cy, x, y);
        
        const lx = cx + Math.cos(rad) * (radius + 10);
        const ly = cy + Math.sin(rad) * (radius + 10);
        const score = Math.round(Number(scores[axis.key]) || 0);
        
        setFont(doc, 7.5, 'bold', DARK);
        doc.text(axis.label, lx, ly, { align: 'center' });
        setFont(doc, 6.5, 'normal', GRAY);
        doc.text(String(score), lx, ly + 4, { align: 'center' });
    });
    
    // Data polygon
    const polygon = axes.map(axis => {
        const score = Math.max(0, Math.min(100, Number(scores[axis.key] || 0)));
        const scaledRadius = radius * (score / 100);
        const rad = (axis.angle * Math.PI) / 180;
        return [cx + Math.cos(rad) * scaledRadius, cy + Math.sin(rad) * scaledRadius];
    });
    
    setDraw(doc, GOLD);
    doc.setLineWidth(1.5);
    setFill(doc, [245, 221, 137]);
    doc.setFillColor(212, 175, 55, 0.25);
    const path = polygon.map((pt, idx) => {
        const prev = polygon[idx === 0 ? polygon.length - 1 : idx - 1];
        return [pt[0] - prev[0], pt[1] - prev[1]];
    });
    doc.lines(path, polygon[polygon.length - 1][0], polygon[polygon.length - 1][1], [1, 1], 'FD', true);
    
    // Data point dots
    polygon.forEach(([px, py]) => {
        setFill(doc, GOLD);
        doc.circle(px, py, 1.5, 'F');
    });
}

// ─── Bar Chart ───────────────────────────────────────────────────────────────
export function drawBarChart(doc, data = [], options = {}) {
    const {
        x = 14, y = 44,
        width = 182, barHeight = 8,
        gap = 4,
        maxValue = 100,
        showLabels = true,
        showValues = true,
        color = GOLD,
        bgColor = LIGHT_GRAY,
    } = options;
    
    data.forEach((item, i) => {
        const rowY = y + i * (barHeight + gap + (showLabels ? 5 : 0));
        const pct = Math.max(0, Math.min(1, Number(item.value || 0) / maxValue));
        const barWidth = width * pct;
        
        if (showLabels) {
            setFont(doc, 7.5, 'normal', DARK);
            doc.text(item.label, x, rowY);
        }
        
        const barY = rowY + (showLabels ? 2 : 0);
        
        // Background bar
        setFill(doc, bgColor);
        doc.roundedRect(x, barY, width, barHeight, 1, 1, 'F');
        
        // Fill bar
        if (barWidth > 0.5) {
            setFill(doc, item.color || color);
            doc.roundedRect(x, barY, barWidth, barHeight, 1, 1, 'F');
        }
        
        // Value label
        if (showValues) {
            setFont(doc, 7, 'bold', item.color || color);
            doc.text(String(item.value), x + width + 3, barY + 6);
        }
    });
}

// ─── Trend Graph ─────────────────────────────────────────────────────────────
export function drawTrendGraph(doc, forecast = {}) {
    const chartX = 14, chartY = 50;
    const width = 182, height = 60;
    
    const series = [
        { key: 'lhs', label: 'Life Health Score', color: GOLD, value: forecast?.lhs?.projectedChange || 0 },
        { key: 'focus_cycles', label: 'Focus Cycles', color: BLUE, value: forecast?.focus_cycles?.projectedChange || 0 },
        { key: 'mood', label: 'Mood Score', color: PURPLE, value: forecast?.mood?.projectedChange || 0 },
    ];
    
    const maxMagnitude = Math.max(5, ...series.map(s => Math.abs(s.value)));
    
    // Chart background
    setFill(doc, [248, 248, 252]);
    setDraw(doc, LIGHT_GRAY);
    doc.setLineWidth(0.2);
    doc.roundedRect(chartX, chartY, width, height, 3, 3, 'FD');
    
    // Zero line
    setDraw(doc, [200, 200, 210]);
    doc.setLineWidth(0.3);
    doc.line(chartX + 40, chartY + height / 2, chartX + width - 5, chartY + height / 2);
    
    setFont(doc, 6, 'normal', GRAY);
    doc.text('0', chartX + 35, chartY + height / 2 + 2);
    
    // Series
    series.forEach((s, i) => {
        const rowY = chartY + 12 + i * 15;
        const normalized = (s.value / maxMagnitude) * (height / 2 - 8);
        const startX = chartX + 42;
        const midX = chartX + width / 2;
        const endX = chartX + width - 5;
        
        // Line from center to end
        setDraw(doc, s.color);
        doc.setLineWidth(1.5);
        doc.line(midX, rowY, endX, rowY - normalized);
        
        // Dot at end
        setFill(doc, s.color);
        doc.circle(endX, rowY - normalized, 1.5, 'F');
        
        // Label
        setFont(doc, 7, 'normal', DARK);
        doc.text(s.label, chartX + 5, rowY + 1.5);
        
        // Value
        const val = s.value;
        setFont(doc, 7, 'bold', s.color);
        doc.text(`${val >= 0 ? '+' : ''}${Number(val).toFixed(1)}`, endX + 3, rowY - normalized + 2);
    });
}

// ─── Habit Grid ──────────────────────────────────────────────────────────────
export function drawHabitGrid(doc, habits = [], y = 50) {
    const cols = 7;
    const cellW = 6, cellH = 5;
    const startX = 14;
    const today = new Date();
    const days = Array.from({ length: 30 }, (_, i) => {
        const d = new Date(today);
        d.setDate(today.getDate() - 29 + i);
        return d.toLocaleDateString('en-CA');
    });
    
    // Day labels
    setFont(doc, 5, 'normal', GRAY);
    days.forEach((d, i) => {
        const date = new Date(d);
        if (date.getDay() === 1 || i === 0) {
            doc.text(date.getDate().toString(), startX + 60 + i * (cellW + 1), y - 2);
        }
    });
    
    habits.slice(0, 8).forEach((habit, hi) => {
        const rowY = y + hi * (cellH + 3);
        const completedDates = habit.meta?.completedDates || [];
        const color = habit.meta?.color || '#3B82F6';
        const rgb = hexToRgb(color);
        
        // Habit name
        setFont(doc, 6, 'normal', DARK);
        doc.text(habit.name.substring(0, 10), startX, rowY + cellH - 1);
        
        // Grid cells
        days.forEach((d, di) => {
            const done = completedDates.includes(d);
            const cx = startX + 60 + di * (cellW + 1);
            
            if (done) {
                setFill(doc, rgb || GOLD);
            } else {
                setFill(doc, LIGHT_GRAY);
            }
            doc.roundedRect(cx, rowY, cellW, cellH, 0.5, 0.5, 'F');
        });
        
        // Completion %
        const pct = days.filter(d => completedDates.includes(d)).length;
        setFont(doc, 6, 'bold', rgb || GOLD);
        doc.text(`${pct}/30`, startX + 60 + days.length * (cellW + 1) + 3, rowY + cellH - 1);
    });
}

// ─── Goals Progress ───────────────────────────────────────────────────────────
export function drawGoalsTable(doc, goals = [], y = 50) {
    goals.slice(0, 6).forEach((goal, i) => {
        const rowY = y + i * 22;
        const progress = goal.milestones?.length
            ? Math.round((goal.milestones.filter(m => m.done).length / goal.milestones.length) * 100)
            : 0;
        
        // Card background
        setFill(doc, [250, 250, 252]);
        setDraw(doc, LIGHT_GRAY);
        doc.setLineWidth(0.2);
        doc.roundedRect(14, rowY, 182, 18, 2, 2, 'FD');
        
        // Left accent
        const color = goal.pillar === 'health' ? GREEN :
            goal.pillar === 'career' ? BLUE :
            goal.pillar === 'academic' ? PURPLE : GOLD;
        setFill(doc, color);
        doc.roundedRect(14, rowY, 2, 18, 1, 1, 'F');
        
        // Title
        setFont(doc, 8, 'bold', DARK);
        doc.text((goal.title || 'Untitled Goal').substring(0, 30), 20, rowY + 7);
        
        // Status badge
        const statusColor = goal.status === 'Achieved' ? GREEN :
            goal.status === 'On Track' ? BLUE :
            goal.status === 'At Risk' ? RED : GRAY;
        setFont(doc, 6, 'bold', statusColor);
        doc.text(goal.status || 'Active', 20, rowY + 14);
        
        // Progress bar
        const barX = 100, barW = 80, barH = 4;
        setFill(doc, LIGHT_GRAY);
        doc.roundedRect(barX, rowY + 7, barW, barH, 1, 1, 'F');
        if (progress > 0) {
            setFill(doc, color);
            doc.roundedRect(barX, rowY + 7, barW * (progress / 100), barH, 1, 1, 'F');
        }
        
        setFont(doc, 7, 'bold', color);
        doc.text(`${progress}%`, barX + barW + 3, rowY + 11);
        
        // Pillar tag
        setFont(doc, 6, 'normal', GRAY);
        doc.text((goal.pillar || 'general').toUpperCase(), 20, rowY + 14 + 0.5);
    });
}

// ─── Insight Box ─────────────────────────────────────────────────────────────
export function drawInsightBox(doc, title, lines = [], y, options = {}) {
    const { color = GOLD, bgColor = [252, 250, 240], width = 182, x = 14 } = options;
    const lineHeight = 5;
    const padding = 8;
    const h = padding * 2 + lineHeight * lines.length;
    
    setFill(doc, bgColor);
    setDraw(doc, color);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, width, h, 3, 3, 'FD');
    
    // Left accent
    setFill(doc, color);
    doc.roundedRect(x, y, 3, h, 1.5, 1.5, 'F');
    
    setFont(doc, 8, 'bold', DARK);
    doc.text(title, x + 8, y + padding);
    
    lines.forEach((line, i) => {
        setFont(doc, 7.5, 'normal', GRAY);
        doc.text(`• ${line}`, x + 8, y + padding + lineHeight * (i + 1));
    });
    
    return h;
}

// ─── Empty State ─────────────────────────────────────────────────────────────
export function drawEmptyState(doc, title, y) {
    setFont(doc, 10, 'italic', [180, 180, 190]);
    doc.text(`${title}: Insufficient data for this period.`, 14, y);
}

// ─── Normalize Score ─────────────────────────────────────────────────────────
export function normalizeScore(value) {
    if (value === null || value === undefined || isNaN(value)) return 0;
    return Math.min(100, Math.max(0, Math.round(Number(value))));
}

export function hasData(arr) {
    return Array.isArray(arr) && arr.length > 0;
}

// ─── Date Range ───────────────────────────────────────────────────────────────
export function getDateRange(mode) {
    const d = new Date();
    const today = d.toLocaleDateString('en-CA');
    if (mode === 'week') {
        const dayOfWeek = d.getDay();
        const mondayOffset = dayOfWeek === 0 ? 6 : dayOfWeek - 1;
        const monday = new Date(d);
        monday.setDate(d.getDate() - mondayOffset);
        return { start: monday.toLocaleDateString('en-CA'), end: today };
    }
    if (mode === 'month') {
        const firstDay = new Date(d.getFullYear(), d.getMonth(), 1);
        return { start: firstDay.toLocaleDateString('en-CA'), end: today };
    }
    if (mode === 'quarter') {
        const firstDay = new Date(d.getFullYear(), Math.floor(d.getMonth() / 3) * 3, 1);
        return { start: firstDay.toLocaleDateString('en-CA'), end: today };
    }
    return { start: today, end: today };
}

// ─── Hex to RGB ───────────────────────────────────────────────────────────────
function hexToRgb(hex) {
    if (!hex || !hex.startsWith('#')) return null;
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b];
}
